#!/usr/bin/perl
use strict;
use warnings;
my %pal;
$pal{"0,0,0"} = [0, 0];
$pal{"50,50,50"} = [0, 1];
$pal{"85,85,85"} = [0, 2];
$pal{"119,119,119"} = [0, 3];
$pal{"38,7,14"} = [1, 0];
$pal{"110,48,63"} = [1, 1];
$pal{"144,82,97"} = [1, 2];
$pal{"165,116,131"} = [1, 3];
$pal{"10,14,79"} = [2, 0];
$pal{"51,63,137"} = [2, 1];
$pal{"85,97,171"} = [2, 2];
$pal{"119,131,179"} = [2, 3];
$pal{"15,31,0"} = [3, 0];
$pal{"68,83,13"} = [3, 1];
$pal{"102,117,47"} = [3, 2];
$pal{"136,151,81"} = [3, 3];
sub bitmap {
  my ($frame) = @_;
  open my $fh, $frame or die "ERROR: Cannot open $frame: $!\n";
  scalar <$fh> for 0,1,2;
  my $data = join "", <$fh>;
  my @pixels;
  push @pixels, $pal{"$1,$2,$3"} || [0,0] while $data =~ m/(\d+) (\d+) (\d+)/g;
  my $line = 0;
  $frame =~ /(\d+)/;
  my $i = ($1 || 0) & 1 ? 1 : 0;
  while (@pixels) {
    print chr(0) x 16 if $line++ == 204;
    my @line = splice @pixels, 0, 160;
    for (my $x = 0; $x < 160; $x += 4) {
      my $byte = $line[$x+0][$i] << 6 | $line[$x+1][$i] << 4 | $line[$x+2][$i] << 2 | $line[$x+3][$i];
      print chr $byte;
    }
    $i = 1 - $i;
  }
}
bitmap($ARGV[0]);
